/*
 * ADCT_Relay.h
 *
 *  Created on: Dec 25, 2016
 *      Author: Administrator
 */

#ifndef DRIVERS_RELAY_INC_ADCT_RELAY_H_
#define DRIVERS_RELAY_INC_ADCT_RELAY_H_


#include "HardwareCfg.h"

void ADCT_Relay_Init(void );

#define ADCT_BGS_RELAY_BUZZER_ON()			GPIO_SetBits(ADCT_BGS_CTRL_RELAY_S01_PORT, ADCT_BGS_CTRL_RELAY_S02)
#define ADCT_BGS_RELAY_BUZZER_OFF()			GPIO_ResetBits(ADCT_BGS_CTRL_RELAY_S01_PORT, ADCT_BGS_CTRL_RELAY_S02)

#define ADCT_BGS_RELAY_LAMP_ON()			GPIO_SetBits(ADCT_BGS_CTRL_RELAY_S02_PORT, ADCT_BGS_CTRL_RELAY_S01)
#define ADCT_BGS_RELAY_LAMP_OFF()			GPIO_ResetBits(ADCT_BGS_CTRL_RELAY_S02_PORT, ADCT_BGS_CTRL_RELAY_S01)


#define ADCT_BGS_AIR_1_2_ON()			{\
    GPIO_ResetBits(ADCT_BGS_CTRL_RELAY_B10_PORT, ADCT_BGS_CTRL_RELAY_B10);\
    GPIO_ResetBits(ADCT_BGS_CTRL_RELAY_B09_PORT, ADCT_BGS_CTRL_RELAY_B09);\
										}
#define ADCT_BGS_AIR_1_2_OFF()			{\
    GPIO_SetBits(ADCT_BGS_CTRL_RELAY_B10_PORT, ADCT_BGS_CTRL_RELAY_B10);\
    GPIO_SetBits(ADCT_BGS_CTRL_RELAY_B09_PORT, ADCT_BGS_CTRL_RELAY_B09);\
}
#define ADCT_BGS_AIR_1_2_READ()	GPIO_ReadOutputDataBit(ADCT_BGS_CTRL_RELAY_B10_PORT, ADCT_BGS_CTRL_RELAY_B10 )

#define ADCT_BGS_AIR_3_4_ON()			{\
    GPIO_ResetBits(ADCT_BGS_CTRL_RELAY_S08_PORT, ADCT_BGS_CTRL_RELAY_S08);\
    GPIO_ResetBits(ADCT_BGS_CTRL_RELAY_S07_PORT, ADCT_BGS_CTRL_RELAY_S07);\
}
#define ADCT_BGS_AIR_3_4_OFF()		{\
    GPIO_SetBits(ADCT_BGS_CTRL_RELAY_S08_PORT, ADCT_BGS_CTRL_RELAY_S08);\
    GPIO_SetBits(ADCT_BGS_CTRL_RELAY_S07_PORT, ADCT_BGS_CTRL_RELAY_S07);\
}
#define ADCT_BGS_AIR_3_4_READ()	GPIO_ReadOutputDataBit(ADCT_BGS_CTRL_RELAY_S08_PORT, ADCT_BGS_CTRL_RELAY_S08 )


#define ADCT_BGS_FAN_ON() {\
		GPIO_SetBits(ADCT_BGS_CTRL_RELAY_S03_PORT, ADCT_BGS_CTRL_RELAY_S03);\
		GPIO_SetBits(ADCT_BGS_CTRL_RELAY_S04_PORT, ADCT_BGS_CTRL_RELAY_S04);\
		GPIO_SetBits(ADCT_BGS_CTRL_RELAY_S05_PORT, ADCT_BGS_CTRL_RELAY_S05);\
		GPIO_SetBits(ADCT_BGS_CTRL_RELAY_S06_PORT, ADCT_BGS_CTRL_RELAY_S06);\
}
#define ADCT_BGS_FAN_OFF() {\
		GPIO_ResetBits(ADCT_BGS_CTRL_RELAY_S03_PORT, ADCT_BGS_CTRL_RELAY_S03);\
		GPIO_ResetBits(ADCT_BGS_CTRL_RELAY_S04_PORT, ADCT_BGS_CTRL_RELAY_S04);\
		GPIO_ResetBits(ADCT_BGS_CTRL_RELAY_S05_PORT, ADCT_BGS_CTRL_RELAY_S05);\
		GPIO_ResetBits(ADCT_BGS_CTRL_RELAY_S06_PORT, ADCT_BGS_CTRL_RELAY_S06);\
}
#define ADCT_BGS_FAN_READ() GPIO_ReadOutputDataBit(ADCT_BGS_CTRL_RELAY_S03_PORT, ADCT_BGS_CTRL_RELAY_S03 )

#define ADCT_BGS_BUZZER_READ() GPIO_ReadOutputDataBit(ADCT_BGS_CTRL_RELAY_S02_PORT, ADCT_BGS_CTRL_RELAY_S02 )
#define ADCT_BGS_LAMP_READ() GPIO_ReadOutputDataBit(ADCT_BGS_CTRL_RELAY_S01_PORT, ADCT_BGS_CTRL_RELAY_S01 )
#endif /* DRIVERS_RELAY_INC_ADCT_RELAY_H_ */
