/*
 ******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 6.0.0   2017-03-20

The MIT License (MIT)
Copyright (c) 2009-2016 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
 ******************************************************************************
 */

/* Includes */
#include <stddef.h>
#include "stm32f10x.h"
#include "ADCT_BGS_FPT_Delay.h"
#include "ADCT_DHT22.h"
#include "ADCT_BGS_BSW_Task.h"
#include "HardwareCfg.h"
#include "ADCT_BGS_BUTTON.h"
#include "tm_stm32_button.h"
#include "ADCT_BGS_State.h"
#include "ADCT_AT24C64.h"
#include "ADCT_Sensor.h"
#include "ADCT_RTC.h"
#include "ADCT_Relay.h"
#include "ADCT_BGS_System.h"
#include "ADCT_BGS_Modbus.h"
#include <PZEM004T.h>
#ifdef SUPPORT_PHSENSOR
#include "ADCT_PhSensor.h"
#endif
#ifdef ADCT_BGS_USE_STANDALONE
#include "ADCT_LCD_16x2.h"
#include "ADCT_BGS_BUTTON.h"
ADCT_LCD_Buffer_Types LCD_Buffer;
#endif
#define DONT_USE_SIMULATION_MODE
//#define SUPPORT_FACTORY_RESET
TM_DELAY_Timer_t *TestTimer;
extern FPT_SystemStatus    GstSystemStatus;
/* System Settings */
extern FPT_UserSetting     GstSystemSetting;
/* System Warning */
extern FPT_SystemWarning   GstSystemWarning;
extern ADCT_BGS_TimerManagedDatatypes g_ADCT_BGS_TimerManager;
extern ADCT_BGS_StateOutputDatatypes g_ADCT_BGS_StateOutput;
extern ADCT_BGS_ASW_TaskDatatypes g_ASW_Task_flag;
double ADCT_PHVal;
void TempTimer_Task(TM_DELAY_Timer_t* timer, void * parameter);
void Simulation_data_BE(void);
uint8_t ui8flag_set_time = 0;
ADCT_BGS_RTC_Types ADCT_BGS_Date_Time_Setting ;
extern volatile uint8_t ADCT_BGS_REBOOT_BOARD ;
uint32_t StartTime;
extern ADCT_BGS_RTC_Types g_ADCT_BGS_Current_RTC;
/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */
void Restart_DHT22(void);
void ADCT_BGS_Initialize_system(void);
void ADCT_BGS_Factory_Reset(void);
int main(void)
{
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_4);
	ADCT_BGS_MODBUS_RS485_Init();
	ADCT_BGS_Systick_Init();
	TM_DELAY_Init();
	ADCT_BGS_DHT22_PWR_Init();
	DHT22_Module_Init_Hardware();
#ifdef ADCT_BGS_USE_STANDALONE
	lcd_Init();
	ADCT_BGS_Button_Init();
	sprintf(LCD_Buffer.lcd_line1, "    ADCTeam     ");
	sprintf(LCD_Buffer.lcd_line2, "DA KHOI TAO XONG");
	(void)lcd_update(LCD_Buffer.lcd_line1, LCD_Buffer.lcd_line2);
#endif
	/* TODO - Add your application code here */
	/* Enable power supply for DHT22 */
	DHT22_01_PWR_ON();
	DHT22_02_PWR_ON();
	ADCT_BGS_ASW_100ms_Init();
	ADCT_BGS_ASW_10ms_Init();
	ADCT_BGS_ASW_1s_Init();
	ADCT_BGS_ASW_1ms_Init();
	ADCT_BGS_Button_Init();
	ADCT_BGS_RTC_Init();
	EEPROM_Init();

	ADCT_BGS_Sensor_Input_Init();
	ADCT_AC_Init();
#ifdef SUPPORT_PHSENSOR
	ADCT_PhSensorInit();

#endif
	ADCT_Relay_Init();
#ifdef SUPPORT_FACTORY_RESET
	ADCT_BGS_Factory_Reset();
#endif
	ADCT_BGS_Initialize_system();
#ifndef DONT_USE_SIMULATION_MODE
	Simulation_data_BE();
#endif
	/* Infinite loop */
	while (1)
	{
#ifdef SUPPORT_PHSENSOR
		if(ADCT_Ph_GetStatus())
		{
			ADCT_PHVal =  ADCT_Ph_getValue();
		}
#endif
#ifdef ADCT_BGS_USE_STANDALONE
		TM_BUTTON_Update();
#endif
		if(g_ASW_Task_flag.ASW_100ms_flag == TRUE)
		{
#ifdef DONT_USE_SIMULATION_MODE
			ADCT_BGS_MODBUS_GetSetting();
#endif

			g_ASW_Task_flag.ASW_100ms_flag = FALSE;
		}
		eMBPoll();
		ADCT_BGS_MODBUS_RS485_UpdateData();
#ifdef DONT_USE_SIMULATION_MODE
		ADCT_BGS_MODBUS_Get_BE_DKG_Data();
#endif
		ADCT_BGS_StateManger();
		ADCT_SystemFPT_RunOutput();
		/* Adding this line for setting RTC time in runtime with support from STLINK debugger and code compile without PRODUCTION CODE mode */
		if(ui8flag_set_time)
		{

			ADCT_BGS_Setting_Date_Time(&ADCT_BGS_Date_Time_Setting);
			ui8flag_set_time = 0;
		}

		if(ADCT_BGS_REBOOT_BOARD)
		{
			ADCT_BGS_Reboot;
			ADCT_BGS_REBOOT_BOARD = FALSE;
		}
		Restart_DHT22();
	}
}

void Simulation_data_BE(void)
{
  GstSystemStatus.mbData.usCurrentMainVoltage =220;
  GstSystemStatus.mbData.usCurrentGenFuel = 30;
  GstSystemStatus.mbData.usCurrentGenVoltage =0;
  GstSystemStatus.mbData.usCurrentGenBatteryVoltage = 24;
  GstSystemStatus.mbData.usCurrentGenCoolantTemp = 200;
  GstSystemStatus.mbData.usCurrentGenEngineSpeed = 1000;
  GstSystemStatus.mbData.usCurrentGenOilPressure = 100;
  GstSystemStatus.mbData.usCurrentGenCurVoltage =200;
  GstSystemStatus.mbData.usCurrentMainFreq = 50;
  GstSystemStatus.mbData.usCurrentGenFreq = 20;
  GstSystemStatus.mbData.usCurrentGenMode = 50;
}

void ADCT_BGS_Initialize_system(void)
{
	static uint16_t HighByte =0, LowByte =0;
	ADCT_BGS_AIR_1_2_OFF();
	ADCT_BGS_AIR_3_4_OFF();
	ADCT_BGS_FAN_OFF();
	ADCT_BGS_RELAY_LAMP_OFF();
	ADCT_BGS_RELAY_BUZZER_OFF();
	// Read parameters saved in EEPROM
	LowByte = ADCT_AT24C64_ReadOneByte(EEPROM_LOW_TEMPERATURE_T1_LOW );
	HighByte = ADCT_AT24C64_ReadOneByte(EEPROM_LOW_TEMPERATURE_T1_HIGH );

	GstSystemSetting.usLowTemperatureT1 = HighByte*256 + LowByte;
	LowByte = ADCT_AT24C64_ReadOneByte(EEPROM_HIGH_TEMPERATURE_T2_LOW );
	HighByte = ADCT_AT24C64_ReadOneByte(EEPROM_HIGH_TEMPERATURE_T2_HIGH );
	GstSystemSetting.usHighTemperatureT2 = (uint16_t)(HighByte*256 + LowByte);

	LowByte = ADCT_AT24C64_ReadOneByte(EEPROM_LOW_HUMIDITY_H1_LOW );
	HighByte = ADCT_AT24C64_ReadOneByte(EEPROM_LOW_HUMIDITY_H1_HIGH);
	GstSystemSetting.usLowHumidityH1 = HighByte*256 + LowByte;

	LowByte = ADCT_AT24C64_ReadOneByte(EEPROM_HIGH_HUMIDITY_H2_LOW);
	HighByte = ADCT_AT24C64_ReadOneByte(EEPROM_HIGH_HUMIDITY_H2_HIGH);
	GstSystemSetting.usHighHumidityH2 = HighByte*256 + LowByte;
	LowByte = ADCT_AT24C64_ReadOneByte(EPPROM_MINSWITCHINGTIME_HOUR);
	HighByte = ADCT_AT24C64_ReadOneByte(EPPROM_MINSWITCHINGTIME_MINUTE);
	GstSystemSetting.ulMinSwitchingTime = LowByte*3600 + HighByte*60;
	LowByte = ADCT_AT24C64_ReadOneByte(EPPROM_SWITCHING_HOUR);
	HighByte = ADCT_AT24C64_ReadOneByte(EPPROM_SWITCHING_MINUTE);
	GstSystemSetting.ulSwitchingTime = LowByte*3600 + HighByte*60;
	LowByte = ADCT_AT24C64_ReadOneByte(EEPROM_FAN_TEMPERATURE_T3_LOW);
	HighByte = ADCT_AT24C64_ReadOneByte(EEPROM_FAN_TEMPERATURE_T3_HIGH);
	GstSystemSetting.usFanTemperatureT3 = HighByte*256 + LowByte;
	GstSystemSetting.ucDoorBurglarEnableAlarm = ADCT_AT24C64_ReadOneByte(EPPROM_DOORBURGLAR_ENABLEALARM);
	GstSystemSetting.ucEnableAlarm = ADCT_AT24C64_ReadOneByte(EPPROM_ENABLE_ALARM);;
	LowByte = ADCT_AT24C64_ReadOneByte(EPPROM_ALARMDURATION_LOW);
	HighByte = ADCT_AT24C64_ReadOneByte(EPPROM_ALARMDURATION_HIGH);
	GstSystemSetting.ulAlarmDuration = HighByte*3600+ LowByte*60;
	LowByte = ADCT_AT24C64_ReadOneByte(EPPROM_GENBATTERYVOLTAGEALARMVALUE_LOW);
	HighByte = ADCT_AT24C64_ReadOneByte(EPPROM_GENBATTERYVOLTAGEALARMVALUE_HIGH);
	GstSystemSetting.usGenBatteryVoltageAlarmValue = HighByte*256 + LowByte;
	LowByte = ADCT_AT24C64_ReadOneByte(EPPROM_GENCOOLANTTEMPALARMVALUE_LOW);
	HighByte = ADCT_AT24C64_ReadOneByte(EPPROM_GENCOOLANTTEMPALARMVALUE_HIGH);
	GstSystemSetting.usGenCoolantTempAlarmValue = HighByte*256 + LowByte;
	LowByte = ADCT_AT24C64_ReadOneByte(EPPROM_GENENGINESPEEDALARMVALUE_LOW);
	HighByte = ADCT_AT24C64_ReadOneByte(EPPROM_GENENGINESPEEDALARMVALUE_HIGH);
	GstSystemSetting.usGenEngineSpeedAlarmValue =  HighByte*256 + LowByte;
	LowByte = ADCT_AT24C64_ReadOneByte(EPPROM_GENFUELLOWVALUE_LOW);
	HighByte = ADCT_AT24C64_ReadOneByte(EPPROM_GENFUELLOWVALUE_HIGH);
	GstSystemSetting.usGenFuelLowValue = HighByte*256 + LowByte;
	LowByte = ADCT_AT24C64_ReadOneByte(EPPROM_GENOILPRESSUREALARMVALUE_LOW);
	HighByte = ADCT_AT24C64_ReadOneByte(EPPROM_GENOILPRESSUREALARMVALUE_HIGH);
	GstSystemSetting.usGenOilPressureAlarmValue = HighByte*256 + LowByte;
	LowByte = ADCT_AT24C64_ReadOneByte(EPPROM_GENVOLTAGEALARMVALUE_LOW);
	HighByte = ADCT_AT24C64_ReadOneByte(EPPROM_GENVOLTAGEALARMVALUE_HIGH);
	GstSystemSetting.usGenVoltageAlarmValue = HighByte*256 + LowByte;
	LowByte = ADCT_AT24C64_ReadOneByte(EPPROM_LOWMAINVOLTAGE_LOW);
	HighByte = ADCT_AT24C64_ReadOneByte(EPPROM_LOWMAINVOLTAGE_HIGH);
	GstSystemSetting.usLowMainVoltage = HighByte*256 + LowByte;

}

void ADCT_BGS_Factory_Reset(void)
{
	// Load default parameter
	ADCT_AT24C64_WriteOneBytes(EEPROM_LOW_TEMPERATURE_T1_LOW,(uint8_t)(DEFAULT_LOWTEMPERATURET1%256));
	ADCT_AT24C64_WriteOneBytes(EEPROM_LOW_TEMPERATURE_T1_HIGH, (uint8_t)(DEFAULT_LOWTEMPERATURET1/256));
	ADCT_AT24C64_WriteOneBytes(EEPROM_HIGH_TEMPERATURE_T2_LOW	,(uint8_t)(DEFAULT_HIGHTEMPERATURET2%256));
	ADCT_AT24C64_WriteOneBytes(EEPROM_HIGH_TEMPERATURE_T2_HIGH	, (uint8_t)(DEFAULT_HIGHTEMPERATURET2/256));
	ADCT_AT24C64_WriteOneBytes(EEPROM_FAN_TEMPERATURE_T3_LOW, (uint8_t)(DEFAULT_FANTEMPERATURET3%256));
	ADCT_AT24C64_WriteOneBytes(EEPROM_FAN_TEMPERATURE_T3_HIGH,(uint8_t)(DEFAULT_FANTEMPERATURET3/256));
	ADCT_AT24C64_WriteOneBytes(EEPROM_LOW_HUMIDITY_H1_LOW, (uint8_t)(DEFAULT_LOWHUMIDITYH1%256));
	ADCT_AT24C64_WriteOneBytes(EEPROM_LOW_HUMIDITY_H1_HIGH, (uint8_t)(DEFAULT_LOWHUMIDITYH1/256));
	ADCT_AT24C64_WriteOneBytes(EEPROM_HIGH_HUMIDITY_H2_LOW, (uint8_t)(DEFAULT_HIGHHUMIDITYH2%256));
	ADCT_AT24C64_WriteOneBytes(EEPROM_HIGH_HUMIDITY_H2_HIGH, (uint8_t)(DEFAULT_HIGHHUMIDITYH2/256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_SWITCHING_HOUR, (uint8_t)(DEFAULT_TIME_CHANGE_HOUR));
	ADCT_AT24C64_WriteOneBytes(EPPROM_SWITCHING_MINUTE, (uint8_t)(DEFAULT_TIME_CHANGE_MINUTE));
	ADCT_AT24C64_WriteOneBytes(EPPROM_DOORBURGLAR_ENABLEALARM, (uint8_t)(DEFAULT_DOORBURGLARENABLEALARM));
	ADCT_AT24C64_WriteOneBytes(EPPROM_ENABLE_ALARM, (uint8_t)(DEFAULT_ENABLEALARM));
	ADCT_AT24C64_WriteOneBytes(EPPROM_ALARMDURATION_LOW, (uint8_t)(DEFAULT_ALARMDURATION%256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_ALARMDURATION_HIGH, (uint8_t)(DEFAULT_ALARMDURATION/256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_GENBATTERYVOLTAGEALARMVALUE_LOW, (uint8_t)(DEFAULT_GENBATTERYVOLTAGEALARMVALUE%256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_GENBATTERYVOLTAGEALARMVALUE_HIGH, (uint8_t)(DEFAULT_GENBATTERYVOLTAGEALARMVALUE/256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_GENCOOLANTTEMPALARMVALUE_LOW, (uint8_t)(DEFAULT_GENCOOLANTTEMPALARMVALUE%256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_GENCOOLANTTEMPALARMVALUE_HIGH, (uint8_t)(DEFAULT_GENCOOLANTTEMPALARMVALUE/256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_GENENGINESPEEDALARMVALUE_LOW,(uint8_t)(DEFAULT_GENENGINESPEEDALARMVALUE%256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_GENENGINESPEEDALARMVALUE_HIGH	,(uint8_t)(DEFAULT_GENENGINESPEEDALARMVALUE/256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_GENFUELLOWVALUE_LOW	,(uint8_t)(DEFAULT_GENFUELLOWVALUE%256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_GENFUELLOWVALUE_HIGH, (uint8_t)(DEFAULT_GENFUELLOWVALUE/256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_GENOILPRESSUREALARMVALUE_LOW, (uint8_t)(DEFAULT_GENOILPRESSUREALARMVALUE%256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_GENOILPRESSUREALARMVALUE_HIGH,(uint8_t)(DEFAULT_GENOILPRESSUREALARMVALUE/256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_GENVOLTAGEALARMVALUE_LOW, (uint8_t)(DEFAULT_GENVOLTAGEALARMVALUE%256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_GENVOLTAGEALARMVALUE_HIGH	,(uint8_t)(DEFAULT_GENVOLTAGEALARMVALUE/256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_LOWMAINVOLTAGE_LOW, (uint8_t)(DEFAULT_LOWMAINVOLTAGE%256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_LOWMAINVOLTAGE_HIGH, (uint8_t)(DEFAULT_LOWMAINVOLTAGE/256));
	ADCT_AT24C64_WriteOneBytes(EPPROM_MINSWITCHINGTIME_HOUR	, (uint8_t)(DEFAULT_MINSWITCHINGTIME_HOUR));
	ADCT_AT24C64_WriteOneBytes(EPPROM_MINSWITCHINGTIME_MINUTE, (uint8_t)(DEFAULT_MINSWITCHINGTIME_MINUTE));
	ADCT_AT24C64_WriteOneBytes(EPPROM_HIGHMAINVOLTAGE_LOW, (uint8_t)(DEFAULT_HIGHMAINVOLTAGE%256)				);
	ADCT_AT24C64_WriteOneBytes(EPPROM_HIGHMAINVOLTAGE_HIGH,(uint8_t)(DEFAULT_HIGHMAINVOLTAGE/256)				);
	ADCT_AT24C64_WriteOneBytes(EPPROM_STAYOFFTIME_HOUR	, (uint8_t)(DEFAULT_STAYOFFTIME_HOUR)				);
	ADCT_AT24C64_WriteOneBytes(EPPROM_STAYOFFTIME_MINUTE, (uint8_t)(DEFAULT_STAYOFFTIME_MINUTE));
	ADCT_AT24C64_WriteOneBytes(EEPROM_DEFAULT_DATE	,DEFAULT_BGS_DATE);
	ADCT_AT24C64_WriteOneBytes(EEPROM_DEFAULT_MONTH	,DEFAULT_BGS_MONTH);
	ADCT_AT24C64_WriteOneBytes(EEPROM_DEFAULT_YEAR	,DEFAULT_BGS_YEAR);
	ADCT_AT24C64_WriteOneBytes(EEPROM_DEFAULT_HOUR	,DEFAULT_BGS_HOUR)	;
	ADCT_AT24C64_WriteOneBytes(EEPROM_DEFAULT_MINUTE,DEFAULT_BGS_MINUTE);
	ADCT_AT24C64_WriteOneBytes(EEPROM_DEFAULT_SECOND,DEFAULT_BGS_SECOND);
	ADCT_AT24C64_WriteOneBytes(EEPROM_ALARM_ID_LOW	, (uint8_t)(DEFAULT_ALARM_ID%256));
	ADCT_AT24C64_WriteOneBytes(EEPROM_ALARM_ID_HIGH	,(uint8_t)(DEFAULT_ALARM_ID/256));
}

void Restart_DHT22(void)
{
	if((g_ADCT_BGS_Current_RTC.RTC_Hour == 20)&&(g_ADCT_BGS_Current_RTC.RTC_Min == 30)&& (g_ADCT_BGS_Current_RTC.RTC_Sec < 30))
	{
		DHT22_01_PWR_OFF();
		DHT22_02_PWR_OFF();
	}
	else
	{
		DHT22_01_PWR_ON();
		DHT22_02_PWR_ON();
	}
}
#ifdef  USE_FULL_ASSERT

/**
 * @brief  Reports the name of the source file and the source line number
 *   where the assert_param error has occurred.
 * @param  file: pointer to the source file name
 * @param  line: assert_param error line source number
 * @retval None
 */
void assert_failed(uint8_t* file, uint32_t line)
{
	/* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

	/* Infinite loop */
	while (1)
	{
	}
}
#endif
